# This is a basic workflow to help you get started with Actions

name: CI1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      -'src/**'
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - edited
  schedule:
    - cron: '0 0 1 * * '

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! Today is "$(date +'%Y-%m-%d-%H-%M-%S')"
